"""create scheduling input schema

Revision ID: 0c48b083c39e
Revises: d90e274c4dfa
Create Date: 2026-09-02 14:14:24.382278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c48b083c39e'
down_revision: Union[str, Sequence[str], None] = 'd90e274c4dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('existing_commitment',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('commitment_date', sa.Date(), nullable=False),
    sa.Column('source_ministry_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_ministry_id IS NOT NULL OR (reason IS NOT NULL AND length(btrim(reason)) > 0)', name=op.f('ck_existing_commitment_provenance_required')),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_existing_commitment_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_ministry_id'], ['ministry.id'], name=op.f('fk_existing_commitment_source_ministry_id_ministry'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_existing_commitment')),
    sa.UniqueConstraint('person_id', 'commitment_date', 'source_ministry_id', name='uq_existing_commitment_person_date_source', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_existing_commitment_commitment_date', 'existing_commitment', ['commitment_date'], unique=False)
    op.create_index('ix_existing_commitment_person_id_commitment_date', 'existing_commitment', ['person_id', 'commitment_date'], unique=False)
    op.create_table('scheduling_period',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('ministry_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('availability_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_scheduling_period_name_not_blank')),
    sa.CheckConstraint('start_date <= end_date', name=op.f('ck_scheduling_period_start_not_after_end')),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministry.id'], name=op.f('fk_scheduling_period_ministry_id_ministry'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduling_period')),
    sa.UniqueConstraint('id', 'ministry_id', name='uq_scheduling_period_id_ministry_id')
    )
    op.create_index('ix_scheduling_period_ministry_id', 'scheduling_period', ['ministry_id'], unique=False)
    op.create_index('uq_scheduling_period_ministry_id_name_lower', 'scheduling_period', ['ministry_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('scheduling_period_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_id', sa.BigInteger(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_kind', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_kind <> 'SPECIAL' OR (name IS NOT NULL AND length(btrim(name)) > 0)", name=op.f('ck_event_special_requires_name')),
    sa.CheckConstraint("event_kind IN ('SUNDAY_SERVICE', 'SPECIAL')", name=op.f('ck_event_event_kind_valid')),
    sa.ForeignKeyConstraint(['scheduling_period_id', 'ministry_id'], ['scheduling_period.id', 'scheduling_period.ministry_id'], name='fk_event_period_ministry', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event')),
    sa.UniqueConstraint('id', 'ministry_id', name='uq_event_id_ministry_id')
    )
    op.create_index('ix_event_event_date', 'event', ['event_date'], unique=False)
    op.create_index('ix_event_scheduling_period_id', 'event', ['scheduling_period_id'], unique=False)
    op.create_table('availability',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('ministry_membership_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_id', sa.BigInteger(), nullable=False),
    sa.Column('availability_state', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability_state IN ('AVAILABLE', 'UNAVAILABLE')", name=op.f('ck_availability_availability_state_valid')),
    sa.ForeignKeyConstraint(['event_id', 'ministry_id'], ['event.id', 'event.ministry_id'], name='fk_availability_event_ministry', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ministry_membership_id', 'ministry_id'], ['ministry_membership.id', 'ministry_membership.ministry_id'], name='fk_availability_membership_ministry', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability')),
    sa.UniqueConstraint('ministry_membership_id', 'event_id', name='uq_availability_ministry_membership_id_event_id')
    )
    op.create_index('ix_availability_event_id', 'availability', ['event_id'], unique=False)
    op.create_table('staffing_requirement',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_role_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_id', sa.BigInteger(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('required_count > 0', name=op.f('ck_staffing_requirement_required_count_positive')),
    sa.ForeignKeyConstraint(['event_id', 'ministry_id'], ['event.id', 'event.ministry_id'], name='fk_staffing_requirement_event_ministry', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ministry_role_id', 'ministry_id'], ['ministry_role.id', 'ministry_role.ministry_id'], name='fk_staffing_requirement_role_ministry', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staffing_requirement')),
    sa.UniqueConstraint('event_id', 'ministry_role_id', name='uq_staffing_requirement_event_id_ministry_role_id')
    )
    op.create_index('ix_staffing_requirement_ministry_role_id', 'staffing_requirement', ['ministry_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_staffing_requirement_ministry_role_id', table_name='staffing_requirement')
    op.drop_table('staffing_requirement')
    op.drop_index('ix_availability_event_id', table_name='availability')
    op.drop_table('availability')
    op.drop_index('ix_event_scheduling_period_id', table_name='event')
    op.drop_index('ix_event_event_date', table_name='event')
    op.drop_table('event')
    op.drop_index('uq_scheduling_period_ministry_id_name_lower', table_name='scheduling_period')
    op.drop_index('ix_scheduling_period_ministry_id', table_name='scheduling_period')
    op.drop_table('scheduling_period')
    op.drop_index('ix_existing_commitment_person_id_commitment_date', table_name='existing_commitment')
    op.drop_index('ix_existing_commitment_commitment_date', table_name='existing_commitment')
    op.drop_table('existing_commitment')
    # ### end Alembic commands ###
