"""create audit event schema

Revision ID: a949a16195e3
Revises: e0bfb11f05b4
Create Date: 2026-09-02 20:59:01.426816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a949a16195e3'
down_revision: Union[str, Sequence[str], None] = 'e0bfb11f05b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('actor_person_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_label', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_table', sa.Text(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_id', sa.BigInteger(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(actor_type = 'PERSON') = (actor_person_id IS NOT NULL)", name=op.f('ck_audit_event_actor_type_matches_actor_person_id')),
    sa.CheckConstraint("action ~ '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'", name=op.f('ck_audit_event_action_shape_valid')),
    sa.CheckConstraint("actor_type IN ('PERSON', 'SYSTEM')", name=op.f('ck_audit_event_actor_type_valid')),
    sa.CheckConstraint("after_values IS NULL OR jsonb_typeof(after_values) = 'object'", name=op.f('ck_audit_event_after_values_is_object')),
    sa.CheckConstraint("before_values IS NULL OR jsonb_typeof(before_values) = 'object'", name=op.f('ck_audit_event_before_values_is_object')),
    sa.CheckConstraint("target_table IN ('person', 'ministry', 'ministry_membership', 'ministry_role', 'role_qualification', 'scheduling_period', 'event', 'staffing_requirement', 'availability', 'existing_commitment', 'schedule', 'schedule_version', 'assignment')", name=op.f('ck_audit_event_target_table_valid')),
    sa.CheckConstraint('before_values IS NOT NULL OR after_values IS NOT NULL', name=op.f('ck_audit_event_payload_present')),
    sa.CheckConstraint('length(btrim(actor_label)) > 0', name=op.f('ck_audit_event_actor_label_not_blank')),
    sa.CheckConstraint('length(btrim(summary)) > 0', name=op.f('ck_audit_event_summary_not_blank')),
    sa.CheckConstraint('reason IS NULL OR length(btrim(reason)) > 0', name=op.f('ck_audit_event_reason_not_blank')),
    sa.CheckConstraint('target_id > 0', name=op.f('ck_audit_event_target_id_positive')),
    sa.ForeignKeyConstraint(['actor_person_id'], ['person.id'], name=op.f('fk_audit_event_actor_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministry.id'], name=op.f('fk_audit_event_ministry_id_ministry'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index('ix_audit_event_actor_person_id_occurred_at', 'audit_event', ['actor_person_id', sa.literal_column('occurred_at DESC')], unique=False, postgresql_where=sa.text('actor_person_id IS NOT NULL'))
    op.create_index('ix_audit_event_ministry_id_occurred_at', 'audit_event', ['ministry_id', sa.literal_column('occurred_at DESC')], unique=False, postgresql_where=sa.text('ministry_id IS NOT NULL'))
    op.create_index('ix_audit_event_occurred_at_id', 'audit_event', [sa.literal_column('occurred_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_audit_event_target_table_target_id_occurred_at', 'audit_event', ['target_table', 'target_id', sa.literal_column('occurred_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_event_target_table_target_id_occurred_at', table_name='audit_event')
    op.drop_index('ix_audit_event_occurred_at_id', table_name='audit_event')
    op.drop_index('ix_audit_event_ministry_id_occurred_at', table_name='audit_event', postgresql_where=sa.text('ministry_id IS NOT NULL'))
    op.drop_index('ix_audit_event_actor_person_id_occurred_at', table_name='audit_event', postgresql_where=sa.text('actor_person_id IS NOT NULL'))
    op.drop_table('audit_event')
    # ### end Alembic commands ###
