"""create core identity and ministry schema

Revision ID: d90e274c4dfa
Revises: 
Create Date: 2026-09-01 17:34:10.014286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90e274c4dfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('church',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_church_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_church'))
    )
    op.create_table('ministry',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('church_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_ministry_name_not_blank')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_ministry_church_id_church'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry'))
    )
    op.create_index('ix_ministry_church_id', 'ministry', ['church_id'], unique=False)
    op.create_index('uq_ministry_church_id_name_lower', 'ministry', ['church_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('person',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('church_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(display_name)) > 0', name=op.f('ck_person_display_name_not_blank')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_person_church_id_church'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person'))
    )
    op.create_index('ix_person_church_id', 'person', ['church_id'], unique=False)
    op.create_index('uq_person_email_lower', 'person', [sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('ministry_membership',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_id', sa.BigInteger(), nullable=False),
    sa.Column('is_ministry_head', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT is_ministry_head OR deactivated_at IS NULL', name=op.f('ck_ministry_membership_head_requires_active_membership')),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministry.id'], name=op.f('fk_ministry_membership_ministry_id_ministry'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_ministry_membership_person_id_person'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry_membership')),
    sa.UniqueConstraint('id', 'ministry_id', name='uq_ministry_membership_id_ministry_id'),
    sa.UniqueConstraint('person_id', 'ministry_id', name='uq_ministry_membership_person_id_ministry_id')
    )
    op.create_index('ix_ministry_membership_head', 'ministry_membership', ['person_id'], unique=False, postgresql_where=sa.text('is_ministry_head'))
    op.create_index('ix_ministry_membership_ministry_id', 'ministry_membership', ['ministry_id'], unique=False)
    op.create_table('ministry_role',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('ministry_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_ministry_role_display_order_non_negative')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_ministry_role_name_not_blank')),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministry.id'], name=op.f('fk_ministry_role_ministry_id_ministry'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry_role')),
    sa.UniqueConstraint('id', 'ministry_id', name='uq_ministry_role_id_ministry_id')
    )
    op.create_index('ix_ministry_role_ministry_id', 'ministry_role', ['ministry_id'], unique=False)
    op.create_index('uq_ministry_role_ministry_id_name_lower', 'ministry_role', ['ministry_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('user_account',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('google_subject', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_user_account_person_id_person'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('google_subject', name='uq_user_account_google_subject'),
    sa.UniqueConstraint('person_id', name='uq_user_account_person_id')
    )
    op.create_index('uq_user_account_email_lower', 'user_account', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('role_qualification',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('ministry_membership_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_role_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_id', sa.BigInteger(), nullable=False),
    sa.Column('is_qualified', sa.Boolean(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by_person_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_person_id'], ['person.id'], name=op.f('fk_role_qualification_decided_by_person_id_person'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ministry_membership_id', 'ministry_id'], ['ministry_membership.id', 'ministry_membership.ministry_id'], name='fk_role_qualification_membership_ministry', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ministry_role_id', 'ministry_id'], ['ministry_role.id', 'ministry_role.ministry_id'], name='fk_role_qualification_role_ministry', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_qualification')),
    sa.UniqueConstraint('ministry_membership_id', 'ministry_role_id', name='uq_role_qualification_membership_role')
    )
    op.create_index('ix_role_qualification_decided_by_person_id', 'role_qualification', ['decided_by_person_id'], unique=False)
    op.create_index('ix_role_qualification_ministry_role_id', 'role_qualification', ['ministry_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_qualification_ministry_role_id', table_name='role_qualification')
    op.drop_index('ix_role_qualification_decided_by_person_id', table_name='role_qualification')
    op.drop_table('role_qualification')
    op.drop_index('uq_user_account_email_lower', table_name='user_account')
    op.drop_table('user_account')
    op.drop_index('uq_ministry_role_ministry_id_name_lower', table_name='ministry_role')
    op.drop_index('ix_ministry_role_ministry_id', table_name='ministry_role')
    op.drop_table('ministry_role')
    op.drop_index('ix_ministry_membership_ministry_id', table_name='ministry_membership')
    op.drop_index('ix_ministry_membership_head', table_name='ministry_membership', postgresql_where=sa.text('is_ministry_head'))
    op.drop_table('ministry_membership')
    op.drop_index('uq_person_email_lower', table_name='person', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('ix_person_church_id', table_name='person')
    op.drop_table('person')
    op.drop_index('uq_ministry_church_id_name_lower', table_name='ministry')
    op.drop_index('ix_ministry_church_id', table_name='ministry')
    op.drop_table('ministry')
    op.drop_table('church')
    # ### end Alembic commands ###
