"""create schedule output schema

Revision ID: e0bfb11f05b4
Revises: 0c48b083c39e
Create Date: 2026-09-02 17:52:11.679947

Implements docs/architecture/schedule-output-data-model.md (revision 2): the
additive UNIQUE (id, scheduling_period_id) parent key on the existing event
table, plus schedule, schedule_version, schedule_version_requirement and
assignment.

Two deliberate corrections to the autogenerated output, both ordering only --
no constraint, column or name was changed. Autogenerate places a standalone
ALTER after every create_table, which is wrong in both directions here because
schedule_version_requirement's fk_..._event_period depends on the new event
parent key:

1. upgrade: the event unique constraint is created first, not last.
2. downgrade: it is dropped last, not first.

Nothing here creates a trigger or a generated column. schedule_version_requirement
is an immutable snapshot: its event_date has no foreign key to event.event_date,
deliberately (see §9 and §13 of the design document).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0bfb11f05b4'
down_revision: Union[str, Sequence[str], None] = '0c48b083c39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted, see the module docstring ###
    # Manual correction 1: the additive parent key on the existing event table
    # is created FIRST. Autogenerate emitted it last, after
    # schedule_version_requirement, whose fk_..._event_period references
    # event (id, scheduling_period_id) -- PostgreSQL requires the referenced
    # unique constraint to exist before the foreign key is created.
    op.create_unique_constraint('uq_event_id_scheduling_period_id', 'event', ['id', 'scheduling_period_id'])
    op.create_table('schedule',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('scheduling_period_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheduling_period_id'], ['scheduling_period.id'], name=op.f('fk_schedule_scheduling_period_id_scheduling_period'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule')),
    sa.UniqueConstraint('id', 'scheduling_period_id', name='uq_schedule_id_scheduling_period_id'),
    sa.UniqueConstraint('scheduling_period_id', name='uq_schedule_scheduling_period_id')
    )
    op.create_table('schedule_version',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduling_period_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amends_version_id', sa.BigInteger(), nullable=True),
    sa.Column('amendment_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'FINALIZED') = (finalized_at IS NOT NULL)", name=op.f('ck_schedule_version_status_finalized_at_agree')),
    sa.CheckConstraint("status IN ('DRAFT', 'REVIEW', 'FINALIZED')", name=op.f('ck_schedule_version_status_valid')),
    sa.CheckConstraint('amends_version_id IS NULL OR (amendment_reason IS NOT NULL AND length(btrim(amendment_reason)) > 0)', name=op.f('ck_schedule_version_amendment_reason_required')),
    sa.CheckConstraint('amends_version_id IS NULL OR amends_version_id <> id', name=op.f('ck_schedule_version_amends_not_self')),
    sa.CheckConstraint('version_number >= 1', name=op.f('ck_schedule_version_version_number_positive')),
    sa.ForeignKeyConstraint(['amends_version_id', 'schedule_id'], ['schedule_version.id', 'schedule_version.schedule_id'], name='fk_schedule_version_amends_same_schedule', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id', 'scheduling_period_id'], ['schedule.id', 'schedule.scheduling_period_id'], name='fk_schedule_version_schedule_period', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_version')),
    sa.UniqueConstraint('id', 'schedule_id', name='uq_schedule_version_id_schedule_id'),
    sa.UniqueConstraint('id', 'scheduling_period_id', name='uq_schedule_version_id_scheduling_period_id'),
    sa.UniqueConstraint('schedule_id', 'version_number', name='uq_schedule_version_schedule_id_version_number')
    )
    op.create_index('ix_schedule_version_authoritative', 'schedule_version', ['schedule_id', sa.literal_column('version_number DESC')], unique=False, postgresql_where=sa.text("status = 'FINALIZED'"))
    op.create_table('schedule_version_requirement',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('schedule_version_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('ministry_role_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduling_period_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_id', sa.BigInteger(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('required_count > 0', name=op.f('ck_schedule_version_requirement_required_count_positive')),
    sa.ForeignKeyConstraint(['event_id', 'ministry_id'], ['event.id', 'event.ministry_id'], name='fk_schedule_version_requirement_event_ministry', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id', 'scheduling_period_id'], ['event.id', 'event.scheduling_period_id'], name='fk_schedule_version_requirement_event_period', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ministry_role_id', 'ministry_id'], ['ministry_role.id', 'ministry_role.ministry_id'], name='fk_schedule_version_requirement_role_ministry', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_version_id', 'scheduling_period_id'], ['schedule_version.id', 'schedule_version.scheduling_period_id'], name='fk_schedule_version_requirement_version_period', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_version_requirement')),
    sa.UniqueConstraint('id', 'schedule_version_id', 'event_id', 'ministry_id', name='uq_schedule_version_requirement_id_version_event_ministry'),
    sa.UniqueConstraint('schedule_version_id', 'event_id', 'ministry_role_id', name='uq_schedule_version_requirement_version_event_role')
    )
    op.create_index('ix_schedule_version_requirement_event_id', 'schedule_version_requirement', ['event_id'], unique=False)
    op.create_table('assignment',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('schedule_version_requirement_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_membership_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_version_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_id', sa.BigInteger(), nullable=False),
    sa.Column('is_override', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(NOT is_override) OR (override_reason IS NOT NULL AND length(btrim(override_reason)) > 0)', name=op.f('ck_assignment_override_reason_required')),
    sa.ForeignKeyConstraint(['ministry_membership_id', 'ministry_id'], ['ministry_membership.id', 'ministry_membership.ministry_id'], name='fk_assignment_membership_ministry', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_version_requirement_id', 'schedule_version_id', 'event_id', 'ministry_id'], ['schedule_version_requirement.id', 'schedule_version_requirement.schedule_version_id', 'schedule_version_requirement.event_id', 'schedule_version_requirement.ministry_id'], name='fk_assignment_requirement_version_event_ministry', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment')),
    sa.UniqueConstraint('schedule_version_id', 'event_id', 'ministry_membership_id', name='uq_assignment_version_event_membership')
    )
    op.create_index('ix_assignment_ministry_membership_id_event_id', 'assignment', ['ministry_membership_id', 'event_id'], unique=False)
    op.create_index('ix_assignment_schedule_version_requirement_id', 'assignment', ['schedule_version_requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted, see the module docstring ###
    op.drop_index('ix_assignment_schedule_version_requirement_id', table_name='assignment')
    op.drop_index('ix_assignment_ministry_membership_id_event_id', table_name='assignment')
    op.drop_table('assignment')
    op.drop_index('ix_schedule_version_requirement_event_id', table_name='schedule_version_requirement')
    op.drop_table('schedule_version_requirement')
    op.drop_index('ix_schedule_version_authoritative', table_name='schedule_version', postgresql_where=sa.text("status = 'FINALIZED'"))
    op.drop_table('schedule_version')
    op.drop_table('schedule')
    # Manual correction 2: the mirror of correction 1. PostgreSQL refuses to
    # drop a unique constraint while a foreign key still depends on it, so the
    # event parent key is dropped LAST, once schedule_version_requirement is
    # gone. Autogenerate emitted it first.
    op.drop_constraint('uq_event_id_scheduling_period_id', 'event', type_='unique')
    # ### end Alembic commands ###
