"""Rendering: a readable roster (real names, local only) and a safe summary.

Two outputs, deliberately separate:

- :func:`render_readable_schedule` -- what the project stakeholder can read without knowing the
  code: each Sunday, each role, the proposed person or ``UNFILLED``. Contains
  real names, so a caller must only ever write it under ``local_data/``.
- :func:`render_privacy_safe_summary` -- counts only, no names, safe to paste
  into a report or commit message.

:func:`compare_to_historical` is structural: it never treats the church's
human roster as the optimization target, only as a reference.
"""

from __future__ import annotations

import datetime
from collections import Counter
from dataclasses import dataclass

from app.scheduling.input import AvailabilityState
from app.scheduling.result import SchedulingResult

from scripts.historical_setup.adapter import AdaptedInput
from scripts.historical_setup.checks import CheckReport
from scripts.historical_setup.model import CANONICAL_ROLE_NAMES, HistoricalDataset

__all__ = [
    "render_readable_schedule",
    "render_privacy_safe_summary",
    "compare_to_historical",
]

_UNFILLED = "UNFILLED"


def _proposed_by_slot(
    adapted: AdaptedInput, result: SchedulingResult
) -> dict[tuple[datetime.date, str], list[str]]:
    out: dict[tuple[datetime.date, str], list[str]] = {}
    for proposal in result.proposed_assignments:
        date = adapted.requirement_date[proposal.requirement_id]
        role = adapted.requirement_role_name[proposal.requirement_id]
        name = adapted.display_name_by_membership.get(
            proposal.membership_id, f"membership {proposal.membership_id}"
        )
        out.setdefault((date, role), []).append(name)
    return out


def render_readable_schedule(
    adapted: AdaptedInput,
    result: SchedulingResult,
    dataset: HistoricalDataset,
) -> str:
    """Plain-text roster. CONTAINS REAL NAMES -- local-only output."""
    si = adapted.scheduling_input
    filled = _proposed_by_slot(adapted, result)

    required_by_slot: Counter[tuple[datetime.date, str]] = Counter()
    for req in si.requirements:
        date = adapted.requirement_date[req.requirement_id]
        role = adapted.requirement_role_name[req.requirement_id]
        required_by_slot[(date, role)] += req.required_count

    lines: list[str] = []
    lines.append(
        f"{dataset.ministry_label} schedule -- generated by solve_schedule()"
        f"  [{dataset.period_label}]"
    )
    lines.append("This file contains real names. Local only -- never commit.")
    lines.append("")

    role_order = {r.name: i for i, r in enumerate(dataset.roles)} or {
        name: i for i, name in enumerate(CANONICAL_ROLE_NAMES)
    }
    for date in adapted.event_id_by_date:
        lines.append(date.strftime("%B %-d, %Y") if hasattr(date, "strftime") else str(date))
        slots = sorted(
            {role for (d, role) in required_by_slot if d == date},
            key=lambda r: role_order.get(r, 99),
        )
        for role in slots:
            need = required_by_slot[(date, role)]
            got = list(filled.get((date, role), []))
            for i in range(need):
                who = got[i] if i < len(got) else _UNFILLED
                label = role if need == 1 else f"{role} ({i + 1})"
                lines.append(f"  {label:<16} {who}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _load_distribution(result: SchedulingResult) -> Counter[int]:
    """How many volunteers carry 0,1,2,... assignments (proposals only)."""
    per_person = Counter(p.membership_id for p in result.proposed_assignments)
    return Counter(per_person.values())


def _per_role_counts(
    adapted: AdaptedInput, result: SchedulingResult
) -> Counter[str]:
    out: Counter[str] = Counter()
    for proposal in result.proposed_assignments:
        out[adapted.requirement_role_name[proposal.requirement_id]] += 1
    return out


def render_privacy_safe_summary(
    adapted: AdaptedInput,
    result: SchedulingResult,
    checks: CheckReport,
    dataset: HistoricalDataset,
    *,
    runtime_seconds: float,
    overlap: "HistoricalComparison | None" = None,
) -> str:
    """Counts only. NO NAMES. Safe to commit / paste into a report."""
    si = adapted.scheduling_input
    metrics = result.metrics
    served = Counter(p.membership_id for p in result.proposed_assignments)
    loads = sorted(served.values())
    n_vol = len(si.candidates)
    served_count = len(served)

    dist = _load_distribution(result)
    dist_str = ", ".join(
        f"{count}x{load}" for load, count in sorted(dist.items())
    ) or "(none)"

    lines = [
        f"Period label:                 {dataset.period_label}",
        f"Sundays:                      {len(si.event_dates)}",
        f"Date range:                   {si.event_dates[0]} .. {si.event_dates[-1]}"
        if si.event_dates else "Date range:                   (none)",
        f"Volunteers:                   {n_vol}",
        f"Lead-qualified volunteers:    {sum(1 for v in dataset.volunteers if v.lead_qualified)}"
        if any(v.qualified_role_names is None for v in dataset.volunteers)
        else f"Volunteers with >=1 role:      "
        f"{sum(1 for v in dataset.volunteers if v.qualified_role_names)}",
        f"Required positions:           {si.total_required_positions}",
        f"Filled (new proposals):       {result.filled_count}",
        f"Unfilled:                     {result.unfilled_count}",
        f"Unavailable-person violations: {len(checks.unavailable_person_violations)}",
        f"NO_RESPONSE policy violations: {len(checks.no_response_violations)}",
        f"Unqualified-lead violations:   {len(checks.unqualified_lead_violations)}",
        f"Church-conflict violations:    {len(checks.church_conflict_violations)}",
        f"One-per-event violations:      {len(checks.one_per_event_violations)}",
        f"Capacity violations:           {len(checks.capacity_violations)}",
        f"Accounting violations:         {len(checks.accounting_violations)}",
        f"Runtime (solver, monotonic):  {runtime_seconds:.3f}s",
        f"Volunteers serving >=1:       {served_count} / {n_vol}",
        f"Assignment load range:        {loads[0] if loads else 0} .. {loads[-1] if loads else 0}",
        f"Load distribution:            {dist_str}",
        f"Target per candidate:         "
        + (
            "none configured"
            if adapted.policy.target_assignments_per_candidate is None
            else f"{adapted.policy.target_assignments_per_candidate} (soft)"
        ),
        f"Target excess total:          "
        + (
            "n/a (no numeric target)"
            if metrics.target_excess_total is None
            else str(metrics.target_excess_total)
        ),
        f"Load balancing:               "
        + ("ON" if adapted.policy.balance_candidate_loads else "OFF"),
        f"Fairness cost (sum load^2):   "
        + (
            "n/a (balancing disabled)"
            if metrics.fairness_cost is None
            else str(metrics.fairness_cost)
        ),
        f"Role-variety cost:            {metrics.role_variety_cost}",
        f"Role-variety roles:           {len(adapted.variety_role_ids)}",
        f"Cross-ministry conflict data: {'present' if dataset.conflict_data_available else 'NOT AVAILABLE from source'}",
    ]

    # Per-role staffing and specialization: for a ministry whose volunteers
    # specialize, "how many people could serve this role at all" is the number
    # that explains a shortfall, and an average load cannot show it.
    per_role = _per_role_counts(adapted, result)
    required_per_role: Counter[str] = Counter()
    for req in si.requirements:
        required_per_role[
            adapted.requirement_role_name[req.requirement_id]
        ] += req.required_count
    role_ids_by_name = adapted.role_id_by_name
    lines.append("")
    lines.append("-- Per role --")
    for role in [r.name for r in dataset.roles if r.is_staffing_position]:
        role_id = role_ids_by_name.get(role)
        eligible = sum(
            1 for c in si.candidates if role_id is not None and c.is_qualified_for(role_id)
        )
        lines.append(
            f"  {role:<14} required {required_per_role.get(role, 0):>3},"
            f" filled {per_role.get(role, 0):>3},"
            f" eligible volunteers {eligible:>3}"
        )
    qualified_counts = Counter(
        sum(
            1
            for r in dataset.roles
            if r.is_staffing_position
            and role_ids_by_name.get(r.name) is not None
            and c.is_qualified_for(role_ids_by_name[r.name])
        )
        for c in si.candidates
    )
    lines.append(
        "  roles-per-volunteer:          "
        + (
            ", ".join(
                f"{count} volunteer(s) eligible for {n} role(s)"
                for n, count in sorted(qualified_counts.items())
            )
            or "(none)"
        )
    )
    lines.append(
        f"  single-role volunteers:       {qualified_counts.get(1, 0)}"
    )
    non_staffing = [r.name for r in dataset.roles if not r.is_staffing_position]
    if non_staffing:
        lines.append(
            f"  recorded but never required:  {', '.join(non_staffing)}"
            " (no positions created)"
        )
    if overlap is not None:
        lines.extend(
            [
                "",
                "-- Reference comparison with the church's historical roster --",
                "(low overlap is not failure: multiple valid schedules exist)",
                f"Historical assignments:       {overlap.historical_total}",
                f"Historical positions filled:  {overlap.historical_filled} / {overlap.historical_required}",
                f"Solver positions filled:      {result.filled_count} / {si.total_required_positions}",
                f"Exact person+Sunday+role match: {overlap.exact_matches} / {overlap.comparable}",
                f"Historical rows invalid under supplied availability/qualification: {overlap.historical_invalid}",
                f"  -- of which unavailable:     {overlap.historical_invalid_unavailable}",
                f"  -- of which unqualified lead: {overlap.historical_invalid_unqualified_lead}",
                f"  -- of which unmatched person: {overlap.historical_unmatched}",
            ]
        )
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Historical comparison
# --------------------------------------------------------------------------


@dataclass(slots=True)
class HistoricalComparison:
    historical_total: int
    historical_required: int
    historical_filled: int
    comparable: int
    exact_matches: int
    historical_invalid: int
    historical_invalid_unavailable: int
    historical_invalid_unqualified_lead: int
    historical_unmatched: int
    notes: list[str]


def compare_to_historical(
    adapted: AdaptedInput,
    result: SchedulingResult,
    dataset: HistoricalDataset,
) -> HistoricalComparison:
    """Structural comparison + a plain overlap statistic.

    An overlap match is the same (person, Sunday, role) appearing in both the
    solver's proposals and the historical roster. This is a *reference* number
    only -- the solver is never tuned to raise it.
    """
    si = adapted.scheduling_input
    name_to_membership: dict[str, int] = {}
    for vol in dataset.volunteers:
        name_to_membership.setdefault(vol.display_name.strip().lower(), vol.membership_id)

    candidates_by_id = {c.membership_id: c for c in si.candidates}

    solver_slots: set[tuple[int, datetime.date, str]] = set()
    for proposal in result.proposed_assignments:
        solver_slots.add(
            (
                proposal.membership_id,
                adapted.requirement_date[proposal.requirement_id],
                adapted.requirement_role_name[proposal.requirement_id],
            )
        )

    exact = 0
    comparable = 0
    invalid = 0
    invalid_unavail = 0
    invalid_unqual = 0
    unmatched = 0
    hist_filled = 0
    notes: list[str] = []

    for h in dataset.historical_assignments:
        hist_filled += 1
        mid = h.membership_id
        if mid is None:
            mid = name_to_membership.get(h.display_name.strip().lower())
        if mid is None:
            unmatched += 1
            continue
        comparable += 1
        if (mid, h.event_date, h.role_name) in solver_slots:
            exact += 1

        cand = candidates_by_id.get(mid)
        if cand is None:
            unmatched += 1
            continue
        event_id = adapted.event_id_by_date.get(h.event_date)
        role_id = adapted.role_id_by_name.get(h.role_name)
        bad = False
        if event_id is not None:
            state = cand.availability_for(event_id)
            if state is AvailabilityState.UNAVAILABLE:
                invalid_unavail += 1
                bad = True
        if role_id is not None and role_id == adapted.lead_role_id:
            if not cand.is_qualified_for(role_id):
                invalid_unqual += 1
                bad = True
        if event_id is not None and cand.is_blocked_on(h.event_date):
            bad = True
        if bad:
            invalid += 1

    return HistoricalComparison(
        historical_total=len(dataset.historical_assignments),
        historical_required=si.total_required_positions,
        historical_filled=hist_filled,
        comparable=comparable,
        exact_matches=exact,
        historical_invalid=invalid,
        historical_invalid_unavailable=invalid_unavail,
        historical_invalid_unqualified_lead=invalid_unqual,
        historical_unmatched=unmatched,
        notes=notes,
    )
